"""User table creation v1

Revision ID: 2d68f52391ef
Revises: 
Create Date: 2024-05-05 02:00:47.418286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d68f52391ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('oauth_channel', sa.String(length=20), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('os_name', sa.String(length=20), nullable=False),
    sa.Column('browser_name', sa.String(length=20), nullable=False),
    sa.Column('client_host', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
